package ru.veider.nasapicture.const

const val TAG = "TAG"
const val WIKI_WORDS_BACKSTACK = "WIKI_WORDS"
const val WIKI_SEARCH_BACKSTACK = "WIKI_SEARCH_WORDS"
const val WIKI_WORDS_COUNT = 10
const val PREFERENCES = "PREFERENCES"
const val THEME_NORMAL = "THEME_NORMAL"
const val THEME_MARSIAN = "THEME_MARSIAN"
const val ANIMATION_DURATION = 1000L

enum class DAY{
    EREYESTERDAY, YESTERDAY, TODAY
}