package ru.veider.nasapicture.ui

const val WIKI_WORDS_BACKSTACK = "WIKI_WORDS"
const val WIKI_SEARCH_BACKSTACK = "WIKI_SEARCH_WORDS"
const val WIKI_WORDS_COUNT = 10
const val PREFERENCES = "PREFERENCES"
const val THEME_GREEN = "THEME_NORMAL"
const val THEME_RED = "THEME_MARSIAN"
const val ANIMATION_DURATION = 1000L

